### ISSUE TITLE
Question For TodoResolver

### ISSUE THREAD

**Issue by wuqinqiang** [zenyui/gqlgen-dataloader#9]
graphql file is no  Todo Type, why generated have a TodoResolver interface?

**Comment by wuqinqiang** [comment]
get

**Comment by LuaxY** [comment]
Do you have this answer?
I have the same issue, I don't know how TodoResolver is generated.

**Comment by LuaxY** [comment]
Ok I find why
`autobind` must be enabled in the config.

And custom model must be provided (not the auto-generated one)
https://github.com/zenyui/gqlgen-dataloader/blob/main/graph/model/todo.go#L7-L9

By replacing `User` by `UserID` the magic happen

**Comment by zenyui** [comment]
Hey @wuqinqiang @LuaxY! 

In general, GqlGen will generate resolver interfaces for graph objects when your struct does not explicitly provide an attribute.

The [Todo object in the graph](https://github.com/zenyui/gqlgen-dataloader/blob/9e47f4af593b0dd4b771d2e5a61d03dd78c37445/schema.graphqls#L9), it has a `user` attribute that returns a `User` type. Since our [Todo model struct](https://github.com/zenyui/gqlgen-dataloader/blob/9e47f4af593b0dd4b771d2e5a61d03dd78c37445/graph/model/todo.go#L3-L10) does not provide a `user` attribute, GqlGen generates a [TodoResolver](https://github.com/zenyui/gqlgen-dataloader/blob/9e47f4af593b0dd4b771d2e5a61d03dd78c37445/graph/generated/generated.go#L80-L82) with a `.User` method that lets us define how to resolve a User given a Todo.

When I fetch a `Todo`, I add the `UserID` to it. If the caller queries the `Todo.user` attribute, GqlGen runs our `TodoResolver.User` [implementation](https://github.com/zenyui/gqlgen-dataloader/blob/main/graph/resolver/schema.resolvers.go#L74-L77) and provides the `Todo` struct as an input.

**Comment by zenyui** [comment]
> Ok I find why `autobind` must be enabled in the config.
> 
> And custom model must be provided (not the auto-generated one) https://github.com/zenyui/gqlgen-dataloader/blob/main/graph/model/todo.go#L7-L9
> 
> By replacing `User` by `UserID` the magic happen

Magic indeed, haha :)

**Comment by zenyui** [comment]
> Ok I find why `autobind` must be enabled in the config.
> 
> And custom model must be provided (not the auto-generated one) https://github.com/zenyui/gqlgen-dataloader/blob/main/graph/model/todo.go#L7-L9
> 
> By replacing `User` by `UserID` the magic happen

One comment on this -- I recommend you autogenerate the models, comment out the fields you would like to lazily resolve, and then run the generate command again. GqlGen will figure out what you want.

**Comment by wuqinqiang** [comment]
thanks~~ @zenyui
